#include "RenderDevice.h"
#include "TextureCache.h"

// fxc-generated bytecode headers (build/generated/shaders/, produced from
// render/shaders/*.hlsl by the CMake "Shader precompilation" section).
#include <LitVS.h>
#include <LitPS.h>
#include <UnlitVS.h>
#include <UnlitPS.h>
#include <HighlightVS.h>
#include <HighlightPS.h>

#include <d3d11sdklayers.h>
#include <DirectXPackedVector.h>
#include <DirectXTex.h>
#include <algorithm>
#include <cmath>
#include <tuple>
#include <vector>
#include <cstring>

using Microsoft::WRL::ComPtr;

namespace nsk
{

namespace
{
    struct Vertex { float pos[3]; float normal[3]; float uv[2]; float color[4]; float tangent[3]; };
    struct LineVertex { float pos[3]; float color[4]; };

    struct CBPerFrameLit
    {
        float viewProj[16];
        float lightDir[3]; float ambient;
        float eyePos[3]; float brightness;
        float parallaxScale; float padFrame[3];
    };
    struct CBPerObjectLit
    {
        float world[16];
        float glowColor[4];     // lighting: emissive rgb (already * emissiveMultiple) + material alpha
                                 // effect:   Base Color rgba
        float spec[4];           // specular color (rgb) + glossiness (a)
        float uvTransform[4];    // UV Scale (xy) + UV Offset (zw)
        float tintColor[4];      // skin/hair tint rgb + multilayer outer reflection strength (w)
        float params[4];         // specStrength|baseColorScale, lightingEffect1, lightingEffect2, envReflection
        float innerParams[4];    // multilayer: inner scale xy, inner thickness, outer refraction
        float falloffParams[4];  // effect: start angle, stop angle, start opacity, stop opacity
        std::uint32_t flags;     // feature bitmask - see shaders/Lit.hlsl's table / kLit* below
        float alphaTest;         // alpha-test threshold, used when kLitAlphaTest is set
        float pad[2];
    };
    struct CBPerFrameUnlit { float viewProj[16]; };
    struct CBPerObjectUnlit { float world[16]; };

    static_assert(sizeof(CBPerFrameLit) == 112, "CBPerFrameLit must match shaders/Lit.hlsl PerFrame layout");
    static_assert(sizeof(CBPerObjectLit) == 192, "CBPerObjectLit must match shaders/Lit.hlsl PerObject layout");

    // gFlags bits - keep in sync with shaders/Lit.hlsl's gFlags table.
    constexpr std::uint32_t kLitHasDiffuse        = 1;
    constexpr std::uint32_t kLitHasNormalMap      = 2;
    constexpr std::uint32_t kLitHasGlowMap        = 4;
    constexpr std::uint32_t kLitHasEmit           = 8;
    constexpr std::uint32_t kLitHasSoftlight      = 16;
    constexpr std::uint32_t kLitHasRimlight       = 32;
    constexpr std::uint32_t kLitHasBacklight      = 64;
    constexpr std::uint32_t kLitHasCubeMap        = 128;
    constexpr std::uint32_t kLitHasEnvMask        = 256;
    constexpr std::uint32_t kLitHasHeightMap      = 512;
    constexpr std::uint32_t kLitHasTintColor      = 1024;
    constexpr std::uint32_t kLitHasSpecular       = 2048;
    constexpr std::uint32_t kLitModelSpaceNormals = 4096;
    constexpr std::uint32_t kLitHasSpecularMap    = 8192;    // t7 = MSN specular map (not backlight)
    constexpr std::uint32_t kLitHasDetailMask     = 16384;   // t3 = face detail mask (not height)
    constexpr std::uint32_t kLitHasTintMask       = 32768;   // t8 = face tint mask
    constexpr std::uint32_t kLitMultiLayer        = 65536;   // t8 = multilayer inner map
    constexpr std::uint32_t kLitIsEffect          = 131072;  // sk_effectshader path; t8 = greyscale palette
    constexpr std::uint32_t kLitEffectUseFalloff  = 262144;
    constexpr std::uint32_t kLitEffectGreyscaleColor = 524288;
    constexpr std::uint32_t kLitEffectGreyscaleAlpha = 1048576;
    constexpr std::uint32_t kLitEffectWeaponBlood = 2097152;
    constexpr std::uint32_t kLitAlphaTest         = 4194304; // NiAlphaProperty alpha test -> clip()
    constexpr std::uint32_t kLitPBR               = 8388608; // Community Shaders True PBR path
    constexpr std::uint32_t kLitPBRSubsurface     = 16777216; // PBR: t7 = subsurface color map
    constexpr std::uint32_t kLitCMParallax        = 33554432; // complex material's alpha carries a real height field
    constexpr std::uint32_t kLitDisableCM         = 67108864; // UI toggle: treat complex materials as vanilla env masks
    constexpr std::uint32_t kLitNoVertexColor     = 134217728; // UI channel: whiten vertex color rgb (VS), keep alpha
    constexpr std::uint32_t kLitUnlit             = 268435456; // UI channel: lighting off - raw textured surface

    void UploadDynamicCB(ID3D11DeviceContext* ctx, ID3D11Buffer* buf, const void* data, std::size_t size)
    {
        if (!ctx || !buf || !data)
            return;
        D3D11_MAPPED_SUBRESOURCE mapped {};
        const HRESULT hr = ctx->Map(buf, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
        if (SUCCEEDED(hr) && mapped.pData)
        {
            std::memcpy(mapped.pData, data, size);
            ctx->Unmap(buf, 0);
        }
    }

    ComPtr<ID3D11Buffer> CreateDynamicCB(ID3D11Device* device, UINT byteSize)
    {
        const D3D11_BUFFER_DESC desc {
            .ByteWidth = byteSize,
            .Usage = D3D11_USAGE_DYNAMIC,
            .BindFlags = D3D11_BIND_CONSTANT_BUFFER,
            .CPUAccessFlags = D3D11_CPU_ACCESS_WRITE,
        };
        ComPtr<ID3D11Buffer> buf;
        device->CreateBuffer(&desc, nullptr, &buf);
        return buf;
    }
}

bool RenderDevice::EnsureInitialized(ID3D11Device* device, ID3D11DeviceContext* context, std::string* error)
{
    if (m_device) // already built by an earlier viewport attach; shared
        return true;
    if (!device || !context)
    {
        if (error) *error = "RenderDevice::EnsureInitialized: null device/context";
        return false;
    }
    m_device = device;
    m_context = context;

    if (!CreateShaders(error))
        return false;
    if (!CreateStateObjects())
    {
        if (error) *error = "RenderDevice: failed to create state objects";
        return false;
    }

    m_cbPerFrame = CreateDynamicCB(m_device.Get(), sizeof(CBPerFrameLit));
    m_cbPerObject = CreateDynamicCB(m_device.Get(), sizeof(CBPerObjectLit));
    m_cbPerFrameUnlit = CreateDynamicCB(m_device.Get(), sizeof(CBPerFrameUnlit));
    m_cbPerObjectUnlit = CreateDynamicCB(m_device.Get(), sizeof(CBPerObjectUnlit));

    // 1x1 fallback textures, mirroring the defaults NifSkope's renderer
    // binds per sampler (renderer.cpp's white/black/gray/default_n): every
    // Sample() call in the lit shader always has a valid resource bound,
    // even before any texture ever loads successfully.
    {
        auto makeSolid = [this](std::uint32_t rgba, ComPtr<ID3D11ShaderResourceView>& out)
        {
            const D3D11_TEXTURE2D_DESC td {
                .Width = 1, .Height = 1, .MipLevels = 1, .ArraySize = 1,
                .Format = DXGI_FORMAT_R8G8B8A8_UNORM,
                .SampleDesc = { .Count = 1 },
                .Usage = D3D11_USAGE_IMMUTABLE,
                .BindFlags = D3D11_BIND_SHADER_RESOURCE,
            };
            const D3D11_SUBRESOURCE_DATA sd { .pSysMem = &rgba, .SysMemPitch = sizeof(rgba) };
            ComPtr<ID3D11Texture2D> tex;
            if (SUCCEEDED(m_device->CreateTexture2D(&td, &sd, &tex)))
                m_device->CreateShaderResourceView(tex.Get(), nullptr, &out);
        };
        makeSolid(0xFFFFFFFFu, m_whiteTexSRV);      // diffuse/env-mask default
        makeSolid(0xFF000000u, m_blackTexSRV);       // glow/backlight default (no contribution)
        makeSolid(0xFFFF8080u, m_flatNormalSRV);     // (0.5,0.5,1,1) ABGR: flat normal + full spec mask; also NifSkope's default_n LightMask stand-in
        makeSolid(0xFFFF00FFu, m_missingTexSRV);     // magenta (1,0,1): a material's diffuse path that fails to RESOLVE renders loudly instead of blending in as white
    }

    BuildIblCubemap();
    BuildGridAndAxesGeometry();

#if defined(_DEBUG)
    // After a GPU hang the debug layer RaiseException(0x87D) on the next
    // API call - usually UploadDynamicCB. Don't break the process; the
    // RenderScene device-removed guard below skips further draws.
    {
        Microsoft::WRL::ComPtr<ID3D11InfoQueue> iq;
        if (SUCCEEDED(m_device.As(&iq)) && iq)
        {
            iq->SetBreakOnSeverity(D3D11_MESSAGE_SEVERITY_CORRUPTION, FALSE);
            iq->SetBreakOnSeverity(D3D11_MESSAGE_SEVERITY_ERROR, FALSE);
        }
    }
#endif

    return true;
}

void RenderDevice::BuildIblCubemap()
{
    // Procedural sky/ground environment cube for the True PBR branch's
    // ambient specular (shaders/Lit.hlsl t9). The viewer has no scene IBL;
    // a vertical gradient - dark warm ground, light horizon, cool bright
    // sky (world +Y up after SceneBuilder's axis correction) - gives
    // metals directional, colored reflections instead of the flat grey a
    // constant Fenv term produced. Each mip is generated with a wider
    // horizon band and pulled toward the sphere mean, so roughness-indexed
    // SampleLevel behaves like a prefiltered radiance chain. The whole
    // chain is normalized to mean luminance 1.0 over the sphere: the
    // shader multiplies it into the already-calibrated ambient term, so
    // dielectric brightness is unchanged by construction.
    constexpr UINT kSize = 64;
    constexpr UINT kMips = 7; // 64 -> 1

    // dir.y for a cube face texel; only the vertical component matters for
    // the gradient. Face order/orientation is the D3D11 TextureCube layout.
    auto faceDirY = [](UINT face, float u, float v) -> float
    {
        float d[3] {};
        switch (face)
        {
        case 0: d[0] =  1; d[1] = -v; d[2] = -u; break; // +X
        case 1: d[0] = -1; d[1] = -v; d[2] =  u; break; // -X
        case 2: d[0] =  u; d[1] =  1; d[2] =  v; break; // +Y
        case 3: d[0] =  u; d[1] = -1; d[2] = -v; break; // -Y
        case 4: d[0] =  u; d[1] = -v; d[2] =  1; break; // +Z
        default: d[0] = -u; d[1] = -v; d[2] = -1; break; // -Z
        }
        return d[1] / std::sqrt(d[0] * d[0] + d[1] * d[1] + d[2] * d[2]);
    };

    // Gradient at vertical component y (-1..1); soften (0..1, from the mip
    // level) widens the ground/sky transition band.
    auto envColor = [](float y, float soften, float rgb[3])
    {
        static constexpr float kGround[3]  = { 0.40f, 0.35f, 0.30f };
        static constexpr float kHorizon[3] = { 0.95f, 0.91f, 0.87f };
        static constexpr float kZenith[3]  = { 0.85f, 1.00f, 1.25f };
        auto smooth = [](float a, float b, float x)
        {
            x = std::clamp((x - a) / (b - a), 0.0f, 1.0f);
            return x * x * (3.0f - 2.0f * x);
        };
        const float band = 0.12f + 0.9f * soften;
        const float up = smooth(-band, band, y);      // ground -> sky
        const float high = smooth(0.0f, 1.0f, y);     // horizon -> zenith
        for (int c = 0; c < 3; ++c)
        {
            const float sky = kHorizon[c] + (kZenith[c] - kHorizon[c]) * high;
            rgb[c] = kGround[c] + (sky - kGround[c]) * up;
        }
    };

    // Pass 1: float RGB per texel of every (face, mip), plus the
    // solid-angle-weighted mean luminance over mip 0.
    std::vector<std::vector<float>> texels(6u * kMips); // rgb triplets
    double lumSum = 0.0, weightSum = 0.0;
    for (UINT face = 0; face < 6; ++face)
    {
        for (UINT mip = 0; mip < kMips; ++mip)
        {
            const UINT s = kSize >> mip;
            const float soften = static_cast<float>(mip) / (kMips - 1);
            auto& data = texels[face * kMips + mip];
            data.resize(static_cast<std::size_t>(s) * s * 3);
            for (UINT yPx = 0; yPx < s; ++yPx)
            {
                for (UINT xPx = 0; xPx < s; ++xPx)
                {
                    const float u = 2.0f * (xPx + 0.5f) / s - 1.0f;
                    const float v = 2.0f * (yPx + 0.5f) / s - 1.0f;
                    float* rgb = &data[(static_cast<std::size_t>(yPx) * s + xPx) * 3];
                    envColor(faceDirY(face, u, v), soften, rgb);
                    if (mip == 0)
                    {
                        // Texel solid angle on the unit cube: (1+u^2+v^2)^-3/2.
                        const double w = std::pow(1.0 + u * u + v * v, -1.5);
                        lumSum += w * (0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2]);
                        weightSum += w;
                    }
                }
            }
        }
    }
    const float norm = (lumSum > 0.0) ? static_cast<float>(weightSum / lumSum) : 1.0f;

    // Pass 2: normalize and pack as half4 in D3D subresource order
    // (face-major: subresource = face * kMips + mip).
    using DirectX::PackedVector::XMConvertFloatToHalf;
    const std::uint16_t kHalfOne = XMConvertFloatToHalf(1.0f);
    std::vector<std::vector<std::uint16_t>> packed(6u * kMips);
    std::vector<D3D11_SUBRESOURCE_DATA> init(6u * kMips);
    for (UINT face = 0; face < 6; ++face)
    {
        for (UINT mip = 0; mip < kMips; ++mip)
        {
            const UINT s = kSize >> mip;
            const auto& src = texels[face * kMips + mip];
            auto& dst = packed[face * kMips + mip];
            dst.resize(static_cast<std::size_t>(s) * s * 4);
            for (std::size_t i = 0; i < static_cast<std::size_t>(s) * s; ++i)
            {
                dst[i * 4 + 0] = XMConvertFloatToHalf(src[i * 3 + 0] * norm);
                dst[i * 4 + 1] = XMConvertFloatToHalf(src[i * 3 + 1] * norm);
                dst[i * 4 + 2] = XMConvertFloatToHalf(src[i * 3 + 2] * norm);
                dst[i * 4 + 3] = kHalfOne;
            }
            init[face * kMips + mip] = {
                .pSysMem = dst.data(),
                .SysMemPitch = s * 4 * static_cast<UINT>(sizeof(std::uint16_t)),
            };
        }
    }

    const D3D11_TEXTURE2D_DESC td {
        .Width = kSize, .Height = kSize, .MipLevels = kMips, .ArraySize = 6,
        .Format = DXGI_FORMAT_R16G16B16A16_FLOAT,
        .SampleDesc = { .Count = 1 },
        .Usage = D3D11_USAGE_IMMUTABLE,
        .BindFlags = D3D11_BIND_SHADER_RESOURCE,
        .MiscFlags = D3D11_RESOURCE_MISC_TEXTURECUBE,
    };
    ComPtr<ID3D11Texture2D> tex;
    if (SUCCEEDED(m_device->CreateTexture2D(&td, init.data(), &tex)))
        m_device->CreateShaderResourceView(tex.Get(), nullptr, &m_iblCubeSRV);
}

bool RenderDevice::CreateShaders(std::string* error)
{
    // Bytecode arrays are generated at build time by fxc from
    // render/shaders/*.hlsl (see the top-level CMakeLists.txt "Shader
    // precompilation" section), replacing the six runtime D3DCompile calls
    // that used to cost ~260ms per viewport. Creating the shader objects
    // from embedded bytecode is sub-millisecond, so per-renderer creation
    // needs no cross-instance cache anymore.
    (void)error;

    m_device->CreateVertexShader(g_LitVS, sizeof(g_LitVS), nullptr, &m_litVS);
    m_device->CreatePixelShader(g_LitPS, sizeof(g_LitPS), nullptr, &m_litPS);
    m_device->CreateVertexShader(g_UnlitVS, sizeof(g_UnlitVS), nullptr, &m_unlitVS);
    m_device->CreatePixelShader(g_UnlitPS, sizeof(g_UnlitPS), nullptr, &m_unlitPS);
    m_device->CreateVertexShader(g_HighlightVS, sizeof(g_HighlightVS), nullptr, &m_highlightVS);
    m_device->CreatePixelShader(g_HighlightPS, sizeof(g_HighlightPS), nullptr, &m_highlightPS);

    D3D11_INPUT_ELEMENT_DESC litLayoutDesc[] =
    {
        { "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, offsetof(Vertex, pos),    D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT, 0, offsetof(Vertex, normal), D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,    0, offsetof(Vertex, uv),     D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, offsetof(Vertex, color), D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "TANGENT",  0, DXGI_FORMAT_R32G32B32_FLOAT, 0, offsetof(Vertex, tangent), D3D11_INPUT_PER_VERTEX_DATA, 0 },
    };
    m_device->CreateInputLayout(litLayoutDesc, 5, g_LitVS, sizeof(g_LitVS), &m_litLayout);
    // The highlight VS consumes the same vertex layout (it only reads
    // POSITION, but the layout must be validated against its own signature).
    m_device->CreateInputLayout(litLayoutDesc, 5, g_HighlightVS, sizeof(g_HighlightVS), &m_highlightLayout);

    D3D11_INPUT_ELEMENT_DESC unlitLayoutDesc[] =
    {
        { "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, offsetof(LineVertex, pos),   D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, offsetof(LineVertex, color), D3D11_INPUT_PER_VERTEX_DATA, 0 },
    };
    m_device->CreateInputLayout(unlitLayoutDesc, 2, g_UnlitVS, sizeof(g_UnlitVS), &m_unlitLayout);

    return true;
}

bool RenderDevice::CreateStateObjects()
{
    const D3D11_BLEND_DESC blendOpaqueDesc {
        .RenderTarget = { {
            .BlendEnable = FALSE,
            .RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL,
        } },
    };
    m_device->CreateBlendState(&blendOpaqueDesc, &m_blendOpaque);

    const D3D11_BLEND_DESC blendAlphaDesc {
        .RenderTarget = { {
            .BlendEnable = TRUE,
            .SrcBlend = D3D11_BLEND_SRC_ALPHA,
            .DestBlend = D3D11_BLEND_INV_SRC_ALPHA,
            .BlendOp = D3D11_BLEND_OP_ADD,
            .SrcBlendAlpha = D3D11_BLEND_ONE,
            .DestBlendAlpha = D3D11_BLEND_ZERO,
            .BlendOpAlpha = D3D11_BLEND_OP_ADD,
            .RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL,
        } },
    };
    m_device->CreateBlendState(&blendAlphaDesc, &m_blendAlpha);

    const D3D11_DEPTH_STENCIL_DESC depthDesc {
        .DepthEnable = TRUE,
        .DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL,
        .DepthFunc = D3D11_COMPARISON_LESS_EQUAL,
    };
    m_device->CreateDepthStencilState(&depthDesc, &m_depthDefault);

    // SLSF2_ZBuffer_Write cleared (fire glows and similar effect overlays):
    // still depth-TESTED against the opaque scene, but leaves no footprint
    // that would cut out geometry drawn after it.
    D3D11_DEPTH_STENCIL_DESC depthNoWriteDesc = depthDesc;
    depthNoWriteDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
    m_device->CreateDepthStencilState(&depthNoWriteDesc, &m_depthNoWrite);

    const D3D11_RASTERIZER_DESC rasterSolid {
        .FillMode = D3D11_FILL_SOLID,
        .CullMode = D3D11_CULL_BACK,
        // With the D3D viewport/projection convention used by this renderer,
        // NIF's outward-facing triangles rasterize clockwise.
        .FrontCounterClockwise = FALSE,
        .DepthClipEnable = TRUE,
    };
    m_device->CreateRasterizerState(&rasterSolid, &m_rasterSolid);

    D3D11_RASTERIZER_DESC rasterNoCull = rasterSolid;
    rasterNoCull.CullMode = D3D11_CULL_NONE; // SLSF2_Double_Sided materials
    m_device->CreateRasterizerState(&rasterNoCull, &m_rasterSolidNoCull);

    // SLSF1_Decal / SLSF1_Dynamic_Decal materials: pull the depth toward the
    // camera so a decal lying on (or a hair above) its base surface always
    // wins the depth test instead of z-fighting it - the D3D equivalent of
    // NifSkope's glPolygonOffset(-1.0, -1.0) (renderer.cpp). The constant
    // term is a few 24-bit-depth ulps rather than GL's single "smallest
    // resolvable difference" unit because the fixed 1..100000 near/far range
    // (NifViewport.cpp) leaves fewer effective depth bits than NifSkope's
    // bounds-fitted planes; visually the offset is still sub-unit at typical
    // framing distances.
    D3D11_RASTERIZER_DESC rasterDecal = rasterSolid;
    rasterDecal.DepthBias = -4;
    rasterDecal.SlopeScaledDepthBias = -1.0f;
    m_device->CreateRasterizerState(&rasterDecal, &m_rasterDecal);

    D3D11_RASTERIZER_DESC rasterDecalNoCull = rasterDecal;
    rasterDecalNoCull.CullMode = D3D11_CULL_NONE;
    m_device->CreateRasterizerState(&rasterDecalNoCull, &m_rasterDecalNoCull);

    D3D11_RASTERIZER_DESC rasterWire = rasterSolid;
    rasterWire.FillMode = D3D11_FILL_WIREFRAME;
    rasterWire.CullMode = D3D11_CULL_NONE;
    m_device->CreateRasterizerState(&rasterWire, &m_rasterWireframe);

    // Selection overlay: wireframe pulled slightly toward the camera so the
    // lines win the depth test against the very surface they lie on (same
    // bias reasoning as rasterDecal above), while still being occluded by
    // OTHER geometry in front of the selected shape.
    D3D11_RASTERIZER_DESC rasterHighlight = rasterWire;
    rasterHighlight.DepthBias = -16;
    rasterHighlight.SlopeScaledDepthBias = -1.0f;
    m_device->CreateRasterizerState(&rasterHighlight, &m_rasterHighlight);

    const D3D11_SAMPLER_DESC sampDesc {
        .Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR,
        .AddressU = D3D11_TEXTURE_ADDRESS_WRAP,
        .AddressV = D3D11_TEXTURE_ADDRESS_WRAP,
        .AddressW = D3D11_TEXTURE_ADDRESS_WRAP,
        .ComparisonFunc = D3D11_COMPARISON_NEVER,
        .MaxLOD = D3D11_FLOAT32_MAX,
    };
    m_device->CreateSamplerState(&sampDesc, &m_sampler);

    return m_blendOpaque && m_blendAlpha && m_depthDefault && m_depthNoWrite && m_rasterSolid && m_rasterSolidNoCull
        && m_rasterDecal && m_rasterDecalNoCull && m_rasterWireframe && m_rasterHighlight && m_sampler;
}

ID3D11BlendState* RenderDevice::GetBlendState(std::uint8_t srcBlend, std::uint8_t dstBlend)
{
    // The common case stays on the prebuilt standard-alpha state.
    if (srcBlend == 6 && dstBlend == 7)
        return m_blendAlpha.Get();

    const std::uint16_t key = static_cast<std::uint16_t>(srcBlend) << 8 | dstBlend;
    auto it = m_blendCache.find(key);
    if (it != m_blendCache.end())
        return it->second.Get();

    // nif.xml AlphaFunction enum -> D3D11_BLEND.
    auto toD3D = [](std::uint8_t f) -> D3D11_BLEND
    {
        switch (f)
        {
        case 0:  return D3D11_BLEND_ONE;
        case 1:  return D3D11_BLEND_ZERO;
        case 2:  return D3D11_BLEND_SRC_COLOR;
        case 3:  return D3D11_BLEND_INV_SRC_COLOR;
        case 4:  return D3D11_BLEND_DEST_COLOR;
        case 5:  return D3D11_BLEND_INV_DEST_COLOR;
        case 6:  return D3D11_BLEND_SRC_ALPHA;
        case 7:  return D3D11_BLEND_INV_SRC_ALPHA;
        case 8:  return D3D11_BLEND_DEST_ALPHA;
        case 9:  return D3D11_BLEND_INV_DEST_ALPHA;
        case 10: return D3D11_BLEND_SRC_ALPHA_SAT;
        default: return D3D11_BLEND_ONE;
        }
    };

    const D3D11_BLEND_DESC desc {
        .RenderTarget = { {
            .BlendEnable = TRUE,
            .SrcBlend = toD3D(srcBlend),
            .DestBlend = toD3D(dstBlend),
            .BlendOp = D3D11_BLEND_OP_ADD,
            .SrcBlendAlpha = D3D11_BLEND_ONE,
            .DestBlendAlpha = D3D11_BLEND_ZERO,
            .BlendOpAlpha = D3D11_BLEND_OP_ADD,
            .RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL,
        } },
    };
    Microsoft::WRL::ComPtr<ID3D11BlendState> state;
    m_device->CreateBlendState(&desc, &state);
    ID3D11BlendState* raw = state.Get();
    m_blendCache.emplace(key, std::move(state));
    return raw ? raw : m_blendAlpha.Get();
}

const GpuMesh* RenderDevice::GetOrCreateGpuMesh(RenderMeshCache& cache, const NifGeometry* geometry)
{
    auto it = cache.meshes.find(geometry);
    if (it != cache.meshes.end())
        return &it->second;

    std::size_t n = geometry->positions.size();
    std::vector<Vertex> verts(n);
    for (std::size_t i = 0; i < n; ++i)
    {
        Vertex& v = verts[i];
        v.pos[0] = geometry->positions[i][0]; v.pos[1] = geometry->positions[i][1]; v.pos[2] = geometry->positions[i][2];
        if (i < geometry->normals.size())
        {
            v.normal[0] = geometry->normals[i][0]; v.normal[1] = geometry->normals[i][1]; v.normal[2] = geometry->normals[i][2];
        }
        else
        {
            v.normal[0] = 0.0f; v.normal[1] = 0.0f; v.normal[2] = 1.0f;
        }
        if (i < geometry->uvs.size())
        {
            v.uv[0] = geometry->uvs[i][0]; v.uv[1] = geometry->uvs[i][1];
        }
        else
        {
            v.uv[0] = 0.0f; v.uv[1] = 0.0f;
        }
        if (i < geometry->colors.size())
        {
            v.color[0] = geometry->colors[i][0]; v.color[1] = geometry->colors[i][1];
            v.color[2] = geometry->colors[i][2]; v.color[3] = geometry->colors[i][3];
        }
        else
        {
            v.color[0] = v.color[1] = v.color[2] = v.color[3] = 1.0f;
        }
        if (i < geometry->tangents.size())
        {
            v.tangent[0] = geometry->tangents[i][0]; v.tangent[1] = geometry->tangents[i][1]; v.tangent[2] = geometry->tangents[i][2];
        }
        else
        {
            // Harmless placeholder: only sampled by the shader when
            // gHasNormalMap is set, which only happens when the material
            // actually resolved a normal texture - a mesh with no tangent
            // data in the file also has no meaningful normal map to apply.
            v.tangent[0] = 1.0f; v.tangent[1] = 0.0f; v.tangent[2] = 0.0f;
        }
    }

    std::vector<std::uint16_t> indices;
    indices.reserve(geometry->triangles.size() * 3);
    for (const Triangle& t : geometry->triangles)
    {
        indices.push_back(t[0]);
        indices.push_back(t[1]);
        indices.push_back(t[2]);
    }

    GpuMesh mesh;
    mesh.indexCount = static_cast<UINT>(indices.size());

    const D3D11_BUFFER_DESC vbDesc {
        .ByteWidth = static_cast<UINT>(sizeof(Vertex) * verts.size()),
        .Usage = D3D11_USAGE_IMMUTABLE,
        .BindFlags = D3D11_BIND_VERTEX_BUFFER,
    };
    const D3D11_SUBRESOURCE_DATA vbData { .pSysMem = verts.data() };
    m_device->CreateBuffer(&vbDesc, &vbData, &mesh.vertexBuffer);

    const D3D11_BUFFER_DESC ibDesc {
        .ByteWidth = static_cast<UINT>(sizeof(std::uint16_t) * indices.size()),
        .Usage = D3D11_USAGE_IMMUTABLE,
        .BindFlags = D3D11_BIND_INDEX_BUFFER,
    };
    const D3D11_SUBRESOURCE_DATA ibData { .pSysMem = indices.data() };
    m_device->CreateBuffer(&ibDesc, &ibData, &mesh.indexBuffer);

    auto [insertedIt, _] = cache.meshes.emplace(geometry, std::move(mesh));
    return &insertedIt->second;
}

const GpuLineMesh* RenderDevice::GetOrCreateLineMesh(RenderMeshCache& cache, const NifGeometry* geometry)
{
    if (auto it = cache.lines.find(geometry); it != cache.lines.end())
        return &it->second;
    if (!geometry || geometry->positions.empty())
        return nullptr;

    // Segment length from the geometry's own local bounds (NifSkope's
    // bounds-relative vector length): scale-consistent per mesh, and the
    // world transform then scales the lines together with the surface.
    Vector3 lo = geometry->positions.front(), hi = lo;
    for (const Vector3& p : geometry->positions)
    {
        for (int a = 0; a < 3; ++a)
        {
            lo[a] = std::min(lo[a], p[a]);
            hi[a] = std::max(hi[a], p[a]);
        }
    }
    const float dx = hi[0] - lo[0], dy = hi[1] - lo[1], dz = hi[2] - lo[2];
    const float radius = 0.5f * std::sqrt(dx * dx + dy * dy + dz * dz);
    const float len = std::max(radius, 1e-3f) * 0.04f;

    const float normalColor[4]  = { 0.25f, 0.75f, 1.0f, 1.0f }; // cyan
    const float tangentColor[4] = { 1.0f, 0.35f, 0.85f, 1.0f }; // magenta

    std::vector<LineVertex> verts;
    verts.reserve((geometry->normals.size() + geometry->tangents.size()) * 2);
    auto pushSegments = [&](const std::vector<Vector3>& dirs, const float (&color)[4])
    {
        const std::size_t count = std::min(dirs.size(), geometry->positions.size());
        for (std::size_t i = 0; i < count; ++i)
        {
            const Vector3& p = geometry->positions[i];
            const Vector3& d = dirs[i];
            verts.push_back({ { p[0], p[1], p[2] }, { color[0], color[1], color[2], color[3] } });
            verts.push_back({ { p[0] + d[0] * len, p[1] + d[1] * len, p[2] + d[2] * len },
                              { color[0], color[1], color[2], color[3] } });
        }
    };

    GpuLineMesh lines;
    pushSegments(geometry->normals, normalColor);
    lines.normalVertexCount = static_cast<UINT>(verts.size());
    lines.tangentVertexStart = lines.normalVertexCount;
    pushSegments(geometry->tangents, tangentColor);
    lines.tangentVertexCount = static_cast<UINT>(verts.size()) - lines.tangentVertexStart;
    if (verts.empty())
        return nullptr; // no normal AND no tangent data - nothing to cache

    const D3D11_BUFFER_DESC desc {
        .ByteWidth = static_cast<UINT>(sizeof(LineVertex) * verts.size()),
        .Usage = D3D11_USAGE_IMMUTABLE,
        .BindFlags = D3D11_BIND_VERTEX_BUFFER,
    };
    const D3D11_SUBRESOURCE_DATA data { .pSysMem = verts.data() };
    if (FAILED(m_device->CreateBuffer(&desc, &data, &lines.vertexBuffer)))
        return nullptr;

    auto [insertedIt, _] = cache.lines.emplace(geometry, std::move(lines));
    return &insertedIt->second;
}

void RenderDevice::BuildGridAndAxesGeometry()
{
    // Port of gltools.cpp's drawGrid()/drawAxes() immediate-mode
    // glBegin(GL_LINES) calls (phase3_tools): a flat 21x21 grid on the XZ
    // plane plus 3 colored axis lines, now baked into one static vertex
    // buffer of colored line segments instead of ~90 per-frame glVertex3f
    // calls.
    std::vector<LineVertex> verts;
    const int halfLines = 10;
    const float step = 20.0f;
    const float extent = halfLines * step;
    const float gridColor[4] = { 0.35f, 0.35f, 0.38f, 1.0f };

    for (int i = -halfLines; i <= halfLines; ++i)
    {
        float coord = static_cast<float>(i) * step;
        verts.push_back({ { coord, 0.0f, -extent }, { gridColor[0], gridColor[1], gridColor[2], gridColor[3] } });
        verts.push_back({ { coord, 0.0f,  extent }, { gridColor[0], gridColor[1], gridColor[2], gridColor[3] } });
        verts.push_back({ { -extent, 0.0f, coord }, { gridColor[0], gridColor[1], gridColor[2], gridColor[3] } });
        verts.push_back({ {  extent, 0.0f, coord }, { gridColor[0], gridColor[1], gridColor[2], gridColor[3] } });
    }
    m_gridVertexCount = static_cast<UINT>(verts.size());
    m_axesVertexStart = m_gridVertexCount;

    const float axisLen = extent * 0.5f;
    auto pushAxis = [&](float x, float y, float z, float r, float g, float b)
    {
        verts.push_back({ { 0.0f, 0.0f, 0.0f }, { r, g, b, 1.0f } });
        verts.push_back({ { x, y, z }, { r, g, b, 1.0f } });
    };
    pushAxis(axisLen, 0, 0, 1.0f, 0.2f, 0.2f); // X - red
    pushAxis(0, axisLen, 0, 0.2f, 1.0f, 0.2f); // Y - green
    pushAxis(0, 0, axisLen, 0.3f, 0.5f, 1.0f); // Z - blue
    m_axesVertexCount = static_cast<UINT>(verts.size()) - m_axesVertexStart;

    const D3D11_BUFFER_DESC desc {
        .ByteWidth = static_cast<UINT>(sizeof(LineVertex) * verts.size()),
        .Usage = D3D11_USAGE_IMMUTABLE,
        .BindFlags = D3D11_BIND_VERTEX_BUFFER,
    };
    const D3D11_SUBRESOURCE_DATA data { .pSysMem = verts.data() };
    m_device->CreateBuffer(&desc, &data, &m_gridAxesVB);
}

void RenderDevice::RenderScene(RenderTarget& target, RenderMeshCache& cache,
                               const std::vector<RenderMesh>& meshes, const RenderSettings& settings,
                               TextureCache* textures)
{
    if (!target.ColorRTV() || !target.DepthDSV() || !m_device || !m_context)
        return;
    if (m_device->GetDeviceRemovedReason() != S_OK)
        return;

    ID3D11RenderTargetView* rtvs[] = { target.ColorRTV() };
    m_context->OMSetRenderTargets(1, rtvs, target.DepthDSV());

    float clear[4] = { settings.clearColor[0], settings.clearColor[1], settings.clearColor[2], settings.clearColor[3] };
    m_context->ClearRenderTargetView(target.ColorRTV(), clear);
    m_context->ClearDepthStencilView(target.DepthDSV(), D3D11_CLEAR_DEPTH | D3D11_CLEAR_STENCIL, 1.0f, 0);

    const D3D11_VIEWPORT vp {
        .TopLeftX = 0.0f, .TopLeftY = 0.0f,
        .Width = static_cast<float>(target.Width()), .Height = static_cast<float>(target.Height()),
        .MinDepth = 0.0f, .MaxDepth = 1.0f,
    };
    m_context->RSSetViewports(1, &vp);

    Matrix4 viewProj = settings.proj * settings.view;

    m_context->OMSetDepthStencilState(m_depthDefault.Get(), 0);
    m_context->RSSetState(settings.wireframe ? m_rasterWireframe.Get() : m_rasterSolid.Get());

    // --- Grid + axes (unlit) ---
    if ((settings.showGrid || settings.showAxes) && m_gridAxesVB)
    {
        m_context->IASetInputLayout(m_unlitLayout.Get());
        m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_LINELIST);
        UINT stride = sizeof(LineVertex), offset = 0;
        ID3D11Buffer* vb = m_gridAxesVB.Get();
        m_context->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
        m_context->VSSetShader(m_unlitVS.Get(), nullptr, 0);
        m_context->PSSetShader(m_unlitPS.Get(), nullptr, 0);
        m_context->OMSetBlendState(m_blendOpaque.Get(), nullptr, 0xFFFFFFFF);

        CBPerFrameUnlit cbFrame;
        std::memcpy(cbFrame.viewProj, viewProj.data(), sizeof(cbFrame.viewProj));
        UploadDynamicCB(m_context.Get(), m_cbPerFrameUnlit.Get(), &cbFrame, sizeof(cbFrame));
        ID3D11Buffer* frameCb = m_cbPerFrameUnlit.Get();
        m_context->VSSetConstantBuffers(0, 1, &frameCb);

        Matrix4 identity;
        CBPerObjectUnlit cbObj;
        std::memcpy(cbObj.world, identity.data(), sizeof(cbObj.world));
        UploadDynamicCB(m_context.Get(), m_cbPerObjectUnlit.Get(), &cbObj, sizeof(cbObj));
        ID3D11Buffer* objCb = m_cbPerObjectUnlit.Get();
        m_context->VSSetConstantBuffers(1, 1, &objCb);

        if (settings.showGrid)
            m_context->Draw(m_gridVertexCount, 0);
        if (settings.showAxes)
            m_context->Draw(m_axesVertexCount, m_axesVertexStart);
    }

    // --- Meshes (lit) ---
    if (!meshes.empty())
    {
        m_context->IASetInputLayout(m_litLayout.Get());
        m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        m_context->VSSetShader(m_litVS.Get(), nullptr, 0);
        m_context->PSSetShader(m_litPS.Get(), nullptr, 0);
        m_context->PSSetSamplers(0, 1, m_sampler.GetAddressOf());
        // Scene-independent IBL stand-in for the PBR ambient specular
        // (t9, see BuildIblCubemap) - bound once, not per material.
        m_context->PSSetShaderResources(9, 1, m_iblCubeSRV.GetAddressOf());

        CBPerFrameLit cbFrame {};
        std::memcpy(cbFrame.viewProj, viewProj.data(), sizeof(cbFrame.viewProj));
        Vector3 lightDir = settings.lightDir; lightDir.normalize();
        cbFrame.lightDir[0] = lightDir[0]; cbFrame.lightDir[1] = lightDir[1]; cbFrame.lightDir[2] = lightDir[2];
        cbFrame.ambient = settings.ambient;
        cbFrame.eyePos[0] = settings.eyePos[0]; cbFrame.eyePos[1] = settings.eyePos[1]; cbFrame.eyePos[2] = settings.eyePos[2];
        cbFrame.brightness = settings.brightness;
        cbFrame.parallaxScale = settings.parallaxHeightScale;
        UploadDynamicCB(m_context.Get(), m_cbPerFrame.Get(), &cbFrame, sizeof(cbFrame));
        ID3D11Buffer* frameCb = m_cbPerFrame.Get();
        m_context->VSSetConstantBuffers(0, 1, &frameCb);
        m_context->PSSetConstantBuffers(0, 1, &frameCb);

        auto drawMesh = [&](const RenderMesh& mesh)
        {
            if (!mesh.geometry)
                return;
            const GpuMesh* gpu = GetOrCreateGpuMesh(cache, mesh.geometry);
            if (!gpu || !gpu->vertexBuffer || gpu->indexCount == 0)
                return;

            const NifMaterial& mat = mesh.material;

            // Refraction materials (fire heat-haze planes and the like) are
            // backbuffer-distortion effects in-engine; drawing their source
            // textures as flat geometry (NifSkope paints them black) only
            // obscures the model, so a preview simply omits them.
            if (mat.hasRefraction)
                return;

            CBPerObjectLit cbObj {};
            std::memcpy(cbObj.world, mesh.worldTransform.data(), sizeof(cbObj.world));
            cbObj.glowColor[0] = mat.emissiveColor[0] * mat.emissiveMultiple;
            cbObj.glowColor[1] = mat.emissiveColor[1] * mat.emissiveMultiple;
            cbObj.glowColor[2] = mat.emissiveColor[2] * mat.emissiveMultiple;
            cbObj.glowColor[3] = mat.alpha;
            cbObj.spec[0] = mat.specularColor[0];
            cbObj.spec[1] = mat.specularColor[1];
            cbObj.spec[2] = mat.specularColor[2];
            cbObj.spec[3] = mat.glossiness;
            cbObj.uvTransform[0] = mat.uvScale[0];
            cbObj.uvTransform[1] = mat.uvScale[1];
            cbObj.uvTransform[2] = mat.uvOffset[0];
            cbObj.uvTransform[3] = mat.uvOffset[1];
            cbObj.tintColor[0] = mat.tintColor[0];
            cbObj.tintColor[1] = mat.tintColor[1];
            cbObj.tintColor[2] = mat.tintColor[2];
            cbObj.tintColor[3] = mat.outerReflectionStrength;
            cbObj.params[0] = mat.specularStrength;
            cbObj.params[1] = mat.lightingEffect1;
            cbObj.params[2] = mat.lightingEffect2;
            cbObj.params[3] = mat.environmentReflection;
            cbObj.innerParams[0] = mat.innerTextureScale[0];
            cbObj.innerParams[1] = mat.innerTextureScale[1];
            cbObj.innerParams[2] = mat.innerThickness;
            cbObj.innerParams[3] = mat.outerRefractionStrength;
            cbObj.falloffParams[0] = mat.falloffStartAngle;
            cbObj.falloffParams[1] = mat.falloffStopAngle;
            cbObj.falloffParams[2] = mat.falloffStartOpacity;
            cbObj.falloffParams[3] = mat.falloffStopOpacity;
            if (mat.isEffectShader)
            {
                // Effect shader repurposes gGlowColor as Base Color (rgba)
                // and gParams.x as Base Color Scale - see shaders/Lit.hlsl.
                cbObj.glowColor[0] = mat.emissiveColor[0];
                cbObj.glowColor[1] = mat.emissiveColor[1];
                cbObj.glowColor[2] = mat.emissiveColor[2];
                cbObj.glowColor[3] = mat.effectEmissiveAlpha;
                cbObj.params[0] = mat.emissiveMultiple;
            }

            // Texture bindings + flag bits. The material's derived has*
            // booleans (see NifMaterial's struct comment) say what the
            // shader flags REQUEST; a texture-backed feature's bit is only
            // set once its texture actually resolves, so a failed load
            // degrades to the un-textured shading path instead of sampling
            // a fallback pretending to be real data.
            auto resolve = [&](const std::string& path, ID3D11ShaderResourceView* fallback) -> std::pair<ID3D11ShaderResourceView*, bool>
            {
                if (textures && !path.empty())
                    if (ID3D11ShaderResourceView* loaded = textures->GetOrLoad(path))
                        return { loaded, true };
                return { fallback, false };
            };
            const std::string kNone;

            auto [diffuseSrv, hasDiffuse] = resolve(mat.diffuseTexture, m_whiteTexSRV.Get());
            if (!hasDiffuse && !mat.diffuseTexture.empty())
            {
                // The material NAMES a diffuse texture but it didn't resolve
                // (missing loose file/archive entry or a failed decode):
                // sample the magenta marker instead of degrading to the
                // untextured white path, so missing content is unmissable.
                // Materials with no diffuse path at all keep the white
                // constant - that's authored, not broken.
                diffuseSrv = m_missingTexSRV.Get();
                hasDiffuse = true;
            }
            auto [normalSrv, hasNormal] = resolve(mat.normalTexture, m_flatNormalSRV.Get());
            auto [cubeSrv, hasCube] = resolve(mat.hasCubeMap ? mat.cubeTexture : kNone, nullptr);
            // t4 is declared as a TextureCube in the shader, so it must never
            // receive a 2D view. Some meshes point the environment-map slot at
            // a plain 2D texture (not a real cube DDS); binding that to the
            // cube slot with the env-map flag set trips the debug layer's
            // cube/2D dimension mismatch (#354) on every draw of that shape.
            // Treat a non-cube resolve as "no cube": bind null + clear the flag,
            // which degrades to the no-environment-reflection path.
            if (hasCube && cubeSrv != nullptr)
            {
                D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc {};
                cubeSrv->GetDesc(&srvDesc);
                if (srvDesc.ViewDimension != D3D11_SRV_DIMENSION_TEXTURECUBE)
                {
                    cubeSrv = nullptr;
                    hasCube = false;
                }
            }
            auto [envMaskSrv, hasEnvMask] = resolve(mat.useEnvironmentMask ? mat.envMaskTexture : kNone, m_whiteTexSRV.Get());

            // t3 is dual-purpose: the parallax height map (shader type 3) or
            // the face detail mask (type 4) - mutually exclusive by type.
            auto [heightSrv, hasHeight] = resolve(
                (mat.hasHeightMap || mat.hasDetailMask) ? mat.heightTexture : kNone, m_blackTexSRV.Get());

            // t7 likewise: the backlight map, or - for MSN materials without
            // backlight - the external specular map (NifSkope renderer.cpp
            // line 779's exact condition).
            const bool wantsSpecMap = mat.hasModelSpaceNormals && mat.hasSpecularMap && !mat.hasBacklight;
            auto [backlightSrv, hasBacklightTex] = resolve(
                (mat.hasBacklight || wantsSpecMap) ? mat.backlightTexture : kNone, m_blackTexSRV.Get());

            // Slot 2 is dual-purpose (see NifMaterial): the glow map when
            // hasGlowMap, the rim/soft LightMask otherwise. NifSkope's
            // LightMask fallback is default_n - flat normal color - which
            // m_flatNormalSRV reproduces.
            auto [glowSrv, hasGlowTex] = resolve(mat.hasGlowMap ? mat.glowTexture : kNone, m_blackTexSRV.Get());
            auto [lightMaskSrv, lightMaskLoaded] = resolve(!mat.hasGlowMap ? mat.glowTexture : kNone, m_flatNormalSRV.Get());
            (void)lightMaskLoaded; // rim/soft stay enabled with the fallback mask, like NifSkope

            // t8 is the per-family auxiliary slot: effect greyscale palette,
            // multilayer inner map, or face tint mask.
            const std::string& auxPath = mat.isEffectShader ? mat.greyscaleTexture
                : (mat.hasMultiLayerParallax || mat.hasTintMask) ? mat.innerTexture
                : kNone;
            auto [auxSrv, hasAux] = resolve(auxPath, m_whiteTexSRV.Get());

            // True PBR re-binds the repurposed slots directly (the vanilla
            // feature gates above never fire for a PBR material): t3 =
            // displacement, t5 = RMAOS, t2 = emissive, t7 = subsurface map.
            // With the UI's True PBR toggle off, the material stays on the
            // legacy bindings/path - the closest vanilla interpretation.
            const bool pbrActive = mat.isPBR && settings.enablePBR;
            if (pbrActive)
            {
                std::tie(heightSrv, hasHeight) = resolve(mat.heightTexture, m_blackTexSRV.Get());
                std::tie(envMaskSrv, hasEnvMask) = resolve(mat.envMaskTexture, m_whiteTexSRV.Get());
                std::tie(glowSrv, hasGlowTex) = resolve(mat.glowTexture, m_blackTexSRV.Get());
                std::tie(backlightSrv, hasBacklightTex) = resolve(mat.backlightTexture, m_blackTexSRV.Get());
            }

            std::uint32_t flags = 0;
            if (hasDiffuse)                           flags |= kLitHasDiffuse;
            if (hasNormal)                            flags |= kLitHasNormalMap;
            if (mat.hasGlowMap && hasGlowTex)         flags |= kLitHasGlowMap;
            if (mat.hasEmittance)                     flags |= kLitHasEmit;
            if (mat.hasSoftlight)                     flags |= kLitHasSoftlight;
            if (mat.hasRimlight)                      flags |= kLitHasRimlight;
            if (mat.hasBacklight && hasBacklightTex)  flags |= kLitHasBacklight;
            if (mat.hasCubeMap && hasCube)            flags |= kLitHasCubeMap;
            if (mat.useEnvironmentMask && hasEnvMask) flags |= kLitHasEnvMask;
            if (mat.hasHeightMap && hasHeight)        flags |= kLitHasHeightMap;
            if (mat.hasTintColor)                     flags |= kLitHasTintColor;
            if (mat.hasSpecular)                      flags |= kLitHasSpecular;
            if (mat.hasModelSpaceNormals)             flags |= kLitModelSpaceNormals;
            if (wantsSpecMap && hasBacklightTex)      flags |= kLitHasSpecularMap;
            if (mat.hasDetailMask && hasHeight)       flags |= kLitHasDetailMask;
            if (mat.hasTintMask && hasAux)            flags |= kLitHasTintMask;
            if (mat.hasMultiLayerParallax && hasAux)  flags |= kLitMultiLayer;
            if (mat.isEffectShader)
            {
                flags |= kLitIsEffect;
                if (mat.useFalloff)                   flags |= kLitEffectUseFalloff;
                if (mat.greyscaleColor && hasAux)     flags |= kLitEffectGreyscaleColor;
                if (mat.greyscaleAlpha && hasAux)     flags |= kLitEffectGreyscaleAlpha;
                if (mat.hasWeaponBlood)               flags |= kLitEffectWeaponBlood;
            }
            if (pbrActive)
            {
                // The PBR shader path reinterprets the per-slot bits (see
                // shaders/Lit.hlsl's table): keep only the texture-presence facts
                // it reads and drop any legacy feature bits the repurposed
                // flags may have set.
                flags &= ~(kLitHasGlowMap | kLitHasHeightMap | kLitHasCubeMap | kLitHasEnvMask
                    | kLitHasSoftlight | kLitHasRimlight | kLitHasBacklight | kLitHasSpecularMap
                    | kLitHasDetailMask | kLitHasTintMask | kLitMultiLayer);
                flags |= kLitPBR;
                // The PBR shader gates its GGX specular on the same bit the
                // legacy path uses, so the Specular channel toggle below
                // covers both paths.
                flags |= kLitHasSpecular;
                if (hasHeight)                              flags |= kLitHasHeightMap; // displacement bound
                if (hasEnvMask)                             flags |= kLitHasEnvMask;   // RMAOS bound
                if (hasGlowTex)                             flags |= kLitHasGlowMap;   // emissive map bound
                if (mat.pbrSubsurface && hasBacklightTex)   flags |= kLitPBRSubsurface;
            }
            if (mat.hasAlphaTest)
            {
                flags |= kLitAlphaTest;
                cbObj.alphaTest = mat.alphaTestThreshold;
            }
            // CM parallax runs only when the _m's alpha actually varies:
            // tools emit flat-alpha complex materials for textures with no
            // height source, and POM over a constant height is a uniform
            // view-dependent shift - pure texture swimming (the shader still
            // detects CM itself for the gloss/metal channels).
            if (!mat.isPBR && mat.useEnvironmentMask && hasEnvMask && textures
                && textures->HasComplexMaterialAlpha(mat.envMaskTexture)
                && textures->HasComplexMaterialHeight(mat.envMaskTexture))
            {
                flags |= kLitCMParallax;
            }
            // Extended-material UI toggles: mask parallax/displacement out
            // entirely, and force complex materials down the vanilla
            // env-mask interpretation.
            if (!settings.enableParallax)
                flags &= ~(kLitHasHeightMap | kLitCMParallax);
            if (!settings.enableComplexMaterial)
                flags |= kLitDisableCM;
            // PBR material on the legacy path (True PBR toggle off): its
            // specular fields are repurposed PBR terms (Glossiness = spec
            // level ~0.04, strength = roughness scale, color = subsurface
            // tint), which Blinn-Phong reads as a white sheen over the whole
            // surface. Drop specular so the base albedo/normal show through.
            if (mat.isPBR && !pbrActive)
                flags &= ~kLitHasSpecular;
            // Render-channel toggles: mask one shading input at a time so
            // pane differences can be isolated to a channel.
            if (!settings.enableTextures)     flags &= ~kLitHasDiffuse;
            if (!settings.enableVertexColors) flags |= kLitNoVertexColor;
            if (!settings.enableSpecular)     flags &= ~kLitHasSpecular;
            if (!settings.enableGlow)         flags &= ~(kLitHasEmit | kLitHasGlowMap);
            if (!settings.enableLighting)     flags |= kLitUnlit;
            cbObj.flags = flags;

            ID3D11ShaderResourceView* srvs[9] = {
                diffuseSrv, normalSrv, glowSrv, heightSrv,
                // t4 is a TextureCube; when no cube resolved, bind null with
                // the cube flag cleared (a 2D SRV on a cube slot would be a
                // type mismatch the debug layer flags).
                hasCube ? cubeSrv : nullptr,
                envMaskSrv, lightMaskSrv, backlightSrv, auxSrv,
            };
            m_context->PSSetShaderResources(0, 9, srvs);

            UploadDynamicCB(m_context.Get(), m_cbPerObject.Get(), &cbObj, sizeof(cbObj));
            ID3D11Buffer* objCb = m_cbPerObject.Get();
            m_context->VSSetConstantBuffers(1, 1, &objCb);
            m_context->PSSetConstantBuffers(1, 1, &objCb);

            // NiAlphaProperty's real blend functions (fire glows are
            // SRC_ALPHA/ONE additive - the standard alpha equation would
            // turn them into occluders) and SLSF2_ZBuffer_Write.
            m_context->OMSetBlendState(
                mat.hasAlphaBlend ? GetBlendState(mat.alphaSrcBlend, mat.alphaDstBlend) : m_blendOpaque.Get(),
                nullptr, 0xFFFFFFFF);
            m_context->OMSetDepthStencilState(mat.depthWrite ? m_depthDefault.Get() : m_depthNoWrite.Get(), 0);
            if (!settings.wireframe)
            {
                if (mat.isDecal)
                    m_context->RSSetState(mat.isDoubleSided ? m_rasterDecalNoCull.Get() : m_rasterDecal.Get());
                else
                    m_context->RSSetState(mat.isDoubleSided ? m_rasterSolidNoCull.Get() : m_rasterSolid.Get());
            }

            UINT stride = sizeof(Vertex), offset = 0;
            ID3D11Buffer* vb = gpu->vertexBuffer.Get();
            m_context->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
            m_context->IASetIndexBuffer(gpu->indexBuffer.Get(), DXGI_FORMAT_R16_UINT, 0);
            m_context->DrawIndexed(gpu->indexCount, 0, 0);
        };

        // Two passes: opaque (and alpha-TESTED) geometry first with depth
        // writes, then the alpha-BLENDED shapes in file order - otherwise a
        // no-depth-write additive glow drawn early (file order puts effect
        // shapes anywhere) is simply overwritten by opaque geometry drawn
        // after it. File order within the blended pass mirrors how the
        // engine's BSOrderedNode content is authored; a full back-to-front
        // sort is not attempted.
        for (const RenderMesh& mesh : meshes)
        {
            if (!mesh.material.hasAlphaBlend)
                drawMesh(mesh);
        }
        for (const RenderMesh& mesh : meshes)
        {
            if (mesh.material.hasAlphaBlend)
                drawMesh(mesh);
        }

        // --- Selection wireframe overlay ---
        // Re-draws the picked mesh's triangles as constant-color wireframe
        // over the shaded pass (NifSkope's click-to-select highlight). Depth
        // testing stays on - with m_rasterHighlight's negative bias the lines
        // win against their own surface but geometry in front of the selected
        // shape still occludes them.
        if (settings.selectedMesh >= 0 && static_cast<std::size_t>(settings.selectedMesh) < meshes.size())
        {
            const RenderMesh& sel = meshes[static_cast<std::size_t>(settings.selectedMesh)];
            const GpuMesh* gpu = sel.geometry ? GetOrCreateGpuMesh(cache, sel.geometry) : nullptr;
            if (gpu && gpu->vertexBuffer && gpu->indexCount > 0)
            {
                CBPerFrameUnlit cbFrame;
                std::memcpy(cbFrame.viewProj, viewProj.data(), sizeof(cbFrame.viewProj));
                UploadDynamicCB(m_context.Get(), m_cbPerFrameUnlit.Get(), &cbFrame, sizeof(cbFrame));
                CBPerObjectUnlit cbObj;
                std::memcpy(cbObj.world, sel.worldTransform.data(), sizeof(cbObj.world));
                UploadDynamicCB(m_context.Get(), m_cbPerObjectUnlit.Get(), &cbObj, sizeof(cbObj));

                ID3D11Buffer* frameCb2 = m_cbPerFrameUnlit.Get();
                ID3D11Buffer* objCb2 = m_cbPerObjectUnlit.Get();
                m_context->IASetInputLayout(m_highlightLayout.Get());
                m_context->VSSetShader(m_highlightVS.Get(), nullptr, 0);
                m_context->PSSetShader(m_highlightPS.Get(), nullptr, 0);
                m_context->VSSetConstantBuffers(0, 1, &frameCb2);
                m_context->VSSetConstantBuffers(1, 1, &objCb2);
                m_context->OMSetBlendState(m_blendOpaque.Get(), nullptr, 0xFFFFFFFF);
                m_context->OMSetDepthStencilState(m_depthDefault.Get(), 0); // meshes may have left the no-write state bound
                m_context->RSSetState(m_rasterHighlight.Get());

                UINT stride = sizeof(Vertex), offset = 0;
                ID3D11Buffer* vb = gpu->vertexBuffer.Get();
                m_context->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
                m_context->IASetIndexBuffer(gpu->indexBuffer.Get(), DXGI_FORMAT_R16_UINT, 0);
                m_context->DrawIndexed(gpu->indexCount, 0, 0);
            }
        }

        // --- Vertex normal/tangent line overlays ---
        // NifSkope's gltools drawNormals/drawTangents equivalent: colored
        // line segments from each vertex (cyan = normal, magenta = tangent),
        // for the selected mesh only when one is picked, otherwise for every
        // mesh. Depth-tested, so lines on back faces stay hidden.
        if (settings.showNormals || settings.showTangents)
        {
            m_context->IASetInputLayout(m_unlitLayout.Get());
            m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_LINELIST);
            m_context->VSSetShader(m_unlitVS.Get(), nullptr, 0);
            m_context->PSSetShader(m_unlitPS.Get(), nullptr, 0);
            m_context->OMSetBlendState(m_blendOpaque.Get(), nullptr, 0xFFFFFFFF);
            m_context->OMSetDepthStencilState(m_depthDefault.Get(), 0);
            m_context->RSSetState(m_rasterSolid.Get());

            CBPerFrameUnlit cbFrame;
            std::memcpy(cbFrame.viewProj, viewProj.data(), sizeof(cbFrame.viewProj));
            UploadDynamicCB(m_context.Get(), m_cbPerFrameUnlit.Get(), &cbFrame, sizeof(cbFrame));
            ID3D11Buffer* frameCb2 = m_cbPerFrameUnlit.Get();
            m_context->VSSetConstantBuffers(0, 1, &frameCb2);

            auto drawLines = [&](const RenderMesh& mesh)
            {
                const GpuLineMesh* lines = mesh.geometry ? GetOrCreateLineMesh(cache, mesh.geometry) : nullptr;
                if (!lines || !lines->vertexBuffer)
                    return;

                CBPerObjectUnlit cbObj;
                std::memcpy(cbObj.world, mesh.worldTransform.data(), sizeof(cbObj.world));
                UploadDynamicCB(m_context.Get(), m_cbPerObjectUnlit.Get(), &cbObj, sizeof(cbObj));
                ID3D11Buffer* objCb = m_cbPerObjectUnlit.Get();
                m_context->VSSetConstantBuffers(1, 1, &objCb);

                UINT stride = sizeof(LineVertex), offset = 0;
                ID3D11Buffer* vb = lines->vertexBuffer.Get();
                m_context->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
                if (settings.showNormals && lines->normalVertexCount > 0)
                    m_context->Draw(lines->normalVertexCount, 0);
                if (settings.showTangents && lines->tangentVertexCount > 0)
                    m_context->Draw(lines->tangentVertexCount, lines->tangentVertexStart);
            };

            if (settings.selectedMesh >= 0 && static_cast<std::size_t>(settings.selectedMesh) < meshes.size())
            {
                drawLines(meshes[static_cast<std::size_t>(settings.selectedMesh)]);
            }
            else
            {
                for (const RenderMesh& mesh : meshes)
                    drawLines(mesh);
            }
        }
    }

    // Leave the shared FD2D device context clean: our offscreen color RT
    // must not stay bound when Backplate hands the context to D2D.
    ID3D11RenderTargetView* nullRTV[] = { nullptr };
    m_context->OMSetRenderTargets(1, nullRTV, nullptr);
    ID3D11ShaderResourceView* nullSRVs[10] = {};
    m_context->PSSetShaderResources(0, 10, nullSRVs);
}

} // namespace nsk
